// Generated by scripts/testing/embed_fixtures.py; do not edit.
// Test-only fixture bytes, shared by host widgets and native sandboxes.
// dart format off
import 'dart:convert';

bool fixtureExists(String path) => _documents.containsKey(path);
String fixtureText(String path) =>
    _documents[path] ?? (throw StateError('Unknown contract fixture: $path'));
List<int> fixtureBytes(String path) => utf8.encode(fixtureText(path));

const _documents = <String, String>{
  'bible_v3/rich_translation.json': r'''{
  "translation": "Fixture Bible",
  "abbreviation": "fx",
  "language": "Fixture language",
  "lang": "fx",
  "direction": "LTR",
  "books": [
    {
      "nr": 900000123,
      "name": "Extended Book",
      "chapters": [
        {
          "chapter": 1,
          "name": "Preface",
          "verses": [],
          "titles": [
            {
              "text": "Book preface",
              "type": "main",
              "canonical": false,
              "future_title": false
            }
          ],
          "introduction": [
            {
              "text": "Introduction\nwith its original spacing.",
              "future_intro": 42
            }
          ]
        },
        {
          "chapter": 3,
          "name": "Extended Book 3",
          "verses": [
            {
              "chapter": 3,
              "verse": 7,
              "name": "Extended Book 3:7",
              "text": "  A😀  supplied\tname\nremains.  ",
              "paragraph": true,
              "tokens": [
                {
                  "token": "A😀",
                  "word_start": 1,
                  "word_end": 1,
                  "lemma": {
                    "strong": [
                      "G1",
                      "G2"
                    ],
                    "other": [
                      "lex:one"
                    ]
                  },
                  "morph": {
                    "robinson": [
                      "N-NSM"
                    ]
                  },
                  "xlit": {
                    "beta": [
                      "a"
                    ]
                  },
                  "src": [
                    1,
                    "2,3"
                  ],
                  "gloss": "a",
                  "morphSegmented": true,
                  "source_extra": "preserved"
                },
                {
                  "token": "supplied name",
                  "word_start": 2,
                  "word_end": 3,
                  "type": "x-ketiv",
                  "variant": true
                },
                {
                  "token": "unlocated",
                  "word_start": 0,
                  "word_end": 0
                }
              ],
              "spans": [
                {
                  "tag": "transChange",
                  "span": "supplied",
                  "token_start": 1,
                  "token_end": 1,
                  "word_start": 2,
                  "word_end": 3,
                  "attrs": {
                    "type": "added",
                    "future_attribute": "source"
                  }
                },
                {
                  "tag": "q",
                  "span": "name",
                  "token_start": 1,
                  "token_end": 1,
                  "word_start": 3,
                  "word_end": 3,
                  "attrs": {
                    "who": "#someone"
                  }
                }
              ],
              "future_verse": {
                "nested": [
                  false,
                  0,
                  "kept"
                ]
              }
            },
            {
              "chapter": 3,
              "verse": 9,
              "name": "Extended Book 3:9",
              "text": "Another verse."
            }
          ],
          "editorial": [
            {
              "order": 0,
              "type": "heading",
              "anchor": {
                "verse": 7,
                "edge": "before"
              },
              "text": "Source heading",
              "heading_type": "section",
              "canonical": false
            },
            {
              "order": 1,
              "type": "paragraph",
              "start": 7,
              "end": 9
            },
            {
              "order": 2,
              "type": "future",
              "detail": {
                "kept": true
              }
            }
          ],
          "future_chapter": {
            "preserved": true
          }
        }
      ],
      "titles": [
        {
          "text": "Source title",
          "canonical": true
        }
      ],
      "introduction": [
        {
          "text": "Book introduction."
        }
      ],
      "future_book": [
        1,
        2
      ]
    }
  ],
  "introduction": [
    {
      "text": "Translation introduction."
    }
  ],
  "titles": [
    {
      "text": "Translation title"
    }
  ],
  "future_translation": {
    "x": null
  },
  "encoding": "UTF-8",
  "description": "Contract fixture",
  "distribution_lcsh": "",
  "distribution_version": "",
  "distribution_version_date": "",
  "distribution_abbreviation": "",
  "distribution_about": "",
  "distribution_license": "",
  "distribution_sourcetype": "",
  "distribution_source": "",
  "distribution_versification": "",
  "distribution_history": {}
}
''',
  'commentary_v1.json': r'''{
  "catalogue": {
    "schema": "getbible-commentaries-catalog-v1",
    "version": 1,
    "generated_at": "2026-10-08T00:00:00Z",
    "base_url": "https://commentaries.getbible.net/v1",
    "metadata_url_template": "{commentary}/metadata.json",
    "books_url_template": "{commentary}/books.json",
    "commentary_url_template": "{commentary}.json",
    "book_url_template": "{commentary}/{book}.json",
    "chapter_url_template": "{commentary}/{book}/{chapter}.json",
    "module_count": 1,
    "commentaries": [
      {
        "id": "fixture",
        "name": "Fixture Commentary",
        "language": "en",
        "license": "Public Domain",
        "book_count": 2,
        "chapter_count": 3,
        "entry_count": 6,
        "bytes": 1024
      }
    ]
  },
  "metadata": {
    "schema": "getbible-commentary-metadata-v1",
    "id": "fixture",
    "module": "Fixture",
    "name": "Fixture Commentary",
    "language": "en",
    "version": "1.0",
    "license": "Public Domain",
    "driver": "RawCom",
    "source_type": "SWORD",
    "versification": "KJV",
    "book_count": 2,
    "chapter_count": 3,
    "entry_count": 6,
    "bytes": 1024,
    "storage": {
      "source_entry_count": 0,
      "source_text_bytes": 0,
      "text_bytes": 0,
      "repetition_ratio": 0,
      "chapter_bytes": 0,
      "book_bytes": 0,
      "commentary_bytes": 0,
      "published_bytes": 0
    },
    "books_url": "books.json",
    "book_url_template": "{book}.json",
    "chapter_url_template": "{book}/{chapter}.json",
    "source": "CrossWire SWORD",
    "source_module_url": "https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=Fixture",
    "text_source": "",
    "copyright": "Public-domain source",
    "copyright_holder": "",
    "copyright_contact": {
      "name": "",
      "email": "",
      "address": ""
    },
    "distribution_notes": "",
    "about": "Fixture source attribution.",
    "conversion_note": "Source text converted to plain text.",
    "references": {
      "api": "getbible-v2",
      "versification": "KJV",
      "translations": [
        "kjv"
      ],
      "names": "kjv",
      "language": "en",
      "librarian": [
        "fixture"
      ],
      "aliases": []
    }
  },
  "coverage": {
    "schema": "getbible-commentary-books-v1",
    "commentary": "fixture",
    "language": "en",
    "name": "Fixture Commentary",
    "book_url_template": "{book}.json",
    "chapter_url_template": "{book}/{chapter}.json",
    "book_count": 2,
    "books": [
      {
        "book": 1,
        "name": "Genesis",
        "chapters": [
          0,
          1
        ],
        "entry_count": 5
      },
      {
        "book": 43,
        "name": "John",
        "chapters": [
          2
        ],
        "entry_count": 1
      }
    ]
  },
  "book_intro": {
    "schema": "getbible-commentary-chapter-v1",
    "commentary": "fixture",
    "language": "en",
    "book": 1,
    "name": "Genesis",
    "chapter": 0,
    "entries": [
      {
        "book": 1,
        "chapter": 0,
        "verse": 0,
        "text": "Book introduction.\n\nA second paragraph."
      }
    ]
  },
  "chapter": {
    "schema": "getbible-commentary-chapter-v1",
    "commentary": "fixture",
    "language": "en",
    "book": 1,
    "name": "Genesis",
    "chapter": 1,
    "entries": [
      {
        "book": 1,
        "chapter": 1,
        "verse": 0,
        "text": "Chapter introduction."
      },
      {
        "book": 1,
        "chapter": 1,
        "verse": 3,
        "text": "First ranged comment.\n\n<b>Plain text stays plain.</b>",
        "verses": [
          3,
          4,
          5
        ],
        "osis": "Gen.1.3",
        "references": [
          {
            "ref": "Genesis 1:1-2",
            "osis": "Gen.1.1-Gen.1.2",
            "book": 1,
            "chapter": 1,
            "verse": 1,
            "verses": [
              1,
              2
            ],
            "text": "Gen. 1:1–2"
          },
          {
            "ref": "John 1",
            "osis": "John.1",
            "book": 43,
            "chapter": 1
          }
        ]
      },
      {
        "book": 1,
        "chapter": 1,
        "verse": 5,
        "text": "Second comment for the same verse.",
        "osis": "Gen.1.5"
      },
      {
        "book": 1,
        "chapter": 1,
        "verse": 8,
        "text": "Cross-chapter quotation.",
        "verses": [
          8,
          9
        ],
        "osis": "Gen.1.8",
        "references": [
          {
            "ref": "Genesis 1:1-2",
            "osis": "Gen.1.1-Gen.1.2",
            "book": 1,
            "chapter": 1,
            "verse": 1,
            "verses": [
              1,
              2
            ],
            "text": "Gen. 1:1–2"
          }
        ]
      }
    ]
  },
  "next_chapter": {
    "schema": "getbible-commentary-chapter-v1",
    "commentary": "fixture",
    "language": "en",
    "book": 1,
    "name": "Genesis",
    "chapter": 2,
    "entries": [
      {
        "book": 1,
        "chapter": 2,
        "verse": 1,
        "text": "Cross-chapter quotation.",
        "verses": [
          1,
          2
        ],
        "osis": "Gen.2.1"
      }
    ]
  }
}
''',
  'database_schema_v4.sql': r'''CREATE TABLE IF NOT EXISTS cache_entries(cache_key TEXT PRIMARY KEY NOT NULL, kind TEXT NOT NULL, sha TEXT NOT NULL DEFAULT "", payload TEXT NOT NULL, checked_at INTEGER NOT NULL, cached_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS cache_entries_kind ON cache_entries(kind);
CREATE TABLE IF NOT EXISTS marking_groups(id TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, color TEXT NOT NULL, sort_order INTEGER NOT NULL, is_starter INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS markings(id TEXT PRIMARY KEY NOT NULL, translation TEXT NOT NULL, book_nr INTEGER NOT NULL, chapter_nr INTEGER NOT NULL, verse_nr INTEGER NOT NULL, start_offset INTEGER, end_offset INTEGER, quote TEXT NOT NULL, reference TEXT NOT NULL, group_id TEXT NOT NULL REFERENCES marking_groups(id) ON DELETE CASCADE, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS markings_canonical ON markings(book_nr, chapter_nr, verse_nr);
CREATE INDEX IF NOT EXISTS markings_translation ON markings(translation, book_nr, chapter_nr, verse_nr);
CREATE INDEX IF NOT EXISTS markings_group ON markings(group_id, book_nr, chapter_nr, verse_nr);
CREATE TABLE IF NOT EXISTS notes(id TEXT PRIMARY KEY NOT NULL, canonical_key TEXT NOT NULL UNIQUE, translation TEXT NOT NULL, book_nr INTEGER NOT NULL, chapter_nr INTEGER NOT NULL, verse_nr INTEGER NOT NULL, reference TEXT NOT NULL, text TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS notes_order ON notes(book_nr, chapter_nr, verse_nr);
CREATE TABLE IF NOT EXISTS settings(setting_key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL, updated_at INTEGER NOT NULL);
ALTER TABLE cache_entries ADD COLUMN fresh_until INTEGER;
ALTER TABLE cache_entries ADD COLUMN must_revalidate INTEGER NOT NULL DEFAULT 1;
CREATE TABLE notebooks(id TEXT PRIMARY KEY NOT NULL, title TEXT NOT NULL CHECK(length(title) <= 200), created_at INTEGER NOT NULL CHECK(created_at >= 0), updated_at INTEGER NOT NULL CHECK(updated_at >= created_at), revision INTEGER NOT NULL CHECK(revision > 0));
CREATE INDEX notebooks_recent ON notebooks(updated_at DESC, created_at DESC, id);
CREATE TABLE notebook_blocks(id TEXT PRIMARY KEY NOT NULL, notebook_id TEXT NOT NULL REFERENCES notebooks(id) ON DELETE CASCADE, rank INTEGER NOT NULL CHECK(rank >= 0), text TEXT NOT NULL CHECK(length(text) <= 100000), created_at INTEGER NOT NULL CHECK(created_at >= 0), updated_at INTEGER NOT NULL CHECK(updated_at >= created_at), reference_json TEXT, UNIQUE(notebook_id, rank));
CREATE TABLE notebook_drafts(id TEXT NOT NULL, editor_id TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision > 0), payload TEXT NOT NULL, updated_at INTEGER NOT NULL, base_revision INTEGER CHECK(base_revision > 0), PRIMARY KEY(id, editor_id));
ALTER TABLE marking_groups ADD COLUMN source_json TEXT;
ALTER TABLE markings ADD COLUMN source_json TEXT;
''',
  'dictionaries_v1/dictionaries.json': r'''{
  "schema": "getbible-dictionaries-catalog-v1",
  "version": 1,
  "generated_at": "2026-10-08T12:00:00Z",
  "base_url": "./",
  "metadata_url_template": "{dictionary}/metadata.json",
  "index_url_template": "{dictionary}/index.json",
  "dictionary_url_template": "{dictionary}.json",
  "entry_url_template": "{dictionary}/{entry}.json",
  "module_count": 5,
  "dictionaries": [
    {
      "id": "strongsgreek",
      "name": "Greek lexicon",
      "language": "en",
      "license": "Public Domain",
      "entry_count": 3,
      "unique_key_count": 2,
      "strong_prefix": "G",
      "bytes": 1000
    },
    {
      "id": "strongshebrew",
      "name": "Hebrew lexicon",
      "language": "en",
      "license": "Public Domain",
      "entry_count": 1,
      "unique_key_count": 1,
      "strong_prefix": "H",
      "bytes": 1000
    },
    {
      "id": "oddgreek",
      "name": "Greek keys lexicon",
      "language": "en",
      "license": "Public Domain",
      "entry_count": 1,
      "unique_key_count": 1,
      "strong_prefix": "G",
      "bytes": 1000
    },
    {
      "id": "easton",
      "name": "English dictionary",
      "language": "en",
      "license": "Public Domain",
      "entry_count": 2,
      "unique_key_count": 1,
      "strong_prefix": null,
      "bytes": 1000
    },
    {
      "id": "swedish",
      "name": "Swedish dictionary",
      "language": "sv",
      "license": "Public Domain",
      "entry_count": 1,
      "unique_key_count": 1,
      "strong_prefix": null,
      "bytes": 1000
    }
  ]
}
''',
  'dictionaries_v1/easton/index.json': r'''{
  "schema": "getbible-dictionary-index-v1",
  "dictionary": "easton",
  "language": "en",
  "name": "English dictionary",
  "entry_url_template": "{entry}.json",
  "entry_count": 2,
  "unique_key_count": 1,
  "entries": [
    {
      "id": "kadesh",
      "key": "Kadesh",
      "search": "kadesh",
      "aliases": [
        "Kádésh",
        "Kadesh"
      ]
    },
    {
      "id": "kadesh--2",
      "key": "Kadesh",
      "search": "kadesh",
      "aliases": [
        "Kadesh"
      ],
      "occurrence": 2
    }
  ]
}
''',
  'dictionaries_v1/easton/kadesh--2.json': r'''{
  "schema": "getbible-dictionary-entry-v1",
  "dictionary": "easton",
  "language": "en",
  "id": "kadesh--2",
  "key": "Kadesh",
  "occurrence": 2,
  "aliases": [
    "Kadesh"
  ],
  "text": "Another place."
}
''',
  'dictionaries_v1/easton/kadesh.json': r'''{
  "schema": "getbible-dictionary-entry-v1",
  "dictionary": "easton",
  "language": "en",
  "id": "kadesh",
  "key": "Kadesh",
  "occurrence": 1,
  "aliases": [
    "Kádésh",
    "Kadesh"
  ],
  "text": "A place. <b>Plain text</b>\n\nPreserved paragraphs."
}
''',
  'dictionaries_v1/easton/metadata.json': r'''{
  "schema": "getbible-dictionary-metadata-v1",
  "id": "easton",
  "module": "easton",
  "name": "English dictionary",
  "language": "en",
  "version": "1.0",
  "license": "Public Domain",
  "driver": "RawLD",
  "source_type": "dictionary",
  "entry_count": 2,
  "unique_key_count": 1,
  "strong_prefix": null,
  "bytes": 1000,
  "index_url": "index.json",
  "entry_url_template": "{entry}.json",
  "source": "CrossWire SWORD",
  "source_module_url": "https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=easton",
  "text_source": "Fixture source",
  "copyright": "Public domain fixture",
  "copyright_holder": "",
  "copyright_contact": {
    "name": "",
    "email": "",
    "address": ""
  },
  "distribution_notes": "Fixture only",
  "about": "A study test fixture.",
  "conversion_note": "Converted to plain text.",
  "references": {
    "api": "getbible-v2",
    "versification": "KJV",
    "translations": [
      "kjv"
    ],
    "names": "kjv",
    "language": "en",
    "librarian": [],
    "aliases": []
  }
}
''',
  'dictionaries_v1/oddgreek/index.json': r'''{
  "schema": "getbible-dictionary-index-v1",
  "dictionary": "oddgreek",
  "language": "en",
  "name": "Greek keys lexicon",
  "entry_url_template": "{entry}.json",
  "entry_count": 1,
  "unique_key_count": 1,
  "entries": [
    {
      "id": "published-lemma",
      "key": "ἄλφα",
      "search": "αλφα",
      "aliases": [
        "alpha"
      ]
    }
  ]
}
''',
  'dictionaries_v1/oddgreek/metadata.json': r'''{
  "schema": "getbible-dictionary-metadata-v1",
  "id": "oddgreek",
  "module": "oddgreek",
  "name": "Greek keys lexicon",
  "language": "en",
  "version": "1.0",
  "license": "Public Domain",
  "driver": "RawLD",
  "source_type": "dictionary",
  "entry_count": 1,
  "unique_key_count": 1,
  "strong_prefix": "G",
  "bytes": 1000,
  "index_url": "index.json",
  "entry_url_template": "{entry}.json",
  "source": "CrossWire SWORD",
  "source_module_url": "https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=oddgreek",
  "text_source": "Fixture source",
  "copyright": "Public domain fixture",
  "copyright_holder": "",
  "copyright_contact": {
    "name": "",
    "email": "",
    "address": ""
  },
  "distribution_notes": "Fixture only",
  "about": "A study test fixture.",
  "conversion_note": "Converted to plain text.",
  "references": {
    "api": "getbible-v2",
    "versification": "KJV",
    "translations": [
      "kjv"
    ],
    "names": "kjv",
    "language": "en",
    "librarian": [],
    "aliases": []
  }
}
''',
  'dictionaries_v1/oddgreek/published-lemma.json': r'''{
  "schema": "getbible-dictionary-entry-v1",
  "dictionary": "oddgreek",
  "language": "en",
  "id": "published-lemma",
  "key": "ἄλφα",
  "occurrence": 1,
  "aliases": [
    "alpha"
  ],
  "text": "Advertised prefix, but no token-addressable entry."
}
''',
  'dictionaries_v1/strongsgreek/G3056--2.json': r'''{
  "schema": "getbible-dictionary-entry-v1",
  "dictionary": "strongsgreek",
  "language": "en",
  "id": "G3056--2",
  "key": "λόγος",
  "occurrence": 2,
  "aliases": [
    "G3056",
    "Word"
  ],
  "text": "A distinct definition."
}
''',
  'dictionaries_v1/strongsgreek/G3056.json': r'''{
  "schema": "getbible-dictionary-entry-v1",
  "dictionary": "strongsgreek",
  "language": "en",
  "id": "G3056",
  "key": "λόγος",
  "occurrence": 1,
  "aliases": [
    "G3056",
    "Word"
  ],
  "text": "Word; speech.\n\nA second paragraph.",
  "see_also": [
    {
      "id": "G4487",
      "key": "ῥῆμα"
    }
  ],
  "references": [
    {
      "ref": "John 1:1",
      "osis": "John.1.1",
      "book": 43,
      "chapter": 1,
      "verse": 1,
      "text": "John 1:1"
    }
  ]
}
''',
  'dictionaries_v1/strongsgreek/G4487.json': r'''{
  "schema": "getbible-dictionary-entry-v1",
  "dictionary": "strongsgreek",
  "language": "en",
  "id": "G4487",
  "key": "ῥῆμα",
  "occurrence": 1,
  "aliases": [
    "G4487"
  ],
  "text": "A saying.",
  "backlinks": [
    {
      "id": "G3056",
      "key": "λόγος"
    }
  ]
}
''',
  'dictionaries_v1/strongsgreek/index.json': r'''{
  "schema": "getbible-dictionary-index-v1",
  "dictionary": "strongsgreek",
  "language": "en",
  "name": "Greek lexicon",
  "entry_url_template": "{entry}.json",
  "entry_count": 3,
  "unique_key_count": 2,
  "entries": [
    {
      "id": "G3056",
      "key": "λόγος",
      "search": "λογος",
      "aliases": [
        "G3056",
        "Word"
      ]
    },
    {
      "id": "G3056--2",
      "key": "λόγος",
      "search": "λογος",
      "aliases": [
        "G3056",
        "Word"
      ],
      "occurrence": 2
    },
    {
      "id": "G4487",
      "key": "ῥῆμα",
      "search": "ρημα",
      "aliases": [
        "G4487"
      ]
    }
  ]
}
''',
  'dictionaries_v1/strongsgreek/metadata.json': r'''{
  "schema": "getbible-dictionary-metadata-v1",
  "id": "strongsgreek",
  "module": "strongsgreek",
  "name": "Greek lexicon",
  "language": "en",
  "version": "1.0",
  "license": "Public Domain",
  "driver": "RawLD",
  "source_type": "dictionary",
  "entry_count": 3,
  "unique_key_count": 2,
  "strong_prefix": "G",
  "bytes": 1000,
  "index_url": "index.json",
  "entry_url_template": "{entry}.json",
  "source": "CrossWire SWORD",
  "source_module_url": "https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=strongsgreek",
  "text_source": "Fixture source",
  "copyright": "Public domain fixture",
  "copyright_holder": "",
  "copyright_contact": {
    "name": "",
    "email": "",
    "address": ""
  },
  "distribution_notes": "Fixture only",
  "about": "A study test fixture.",
  "conversion_note": "Converted to plain text.",
  "references": {
    "api": "getbible-v2",
    "versification": "KJV",
    "translations": [
      "kjv"
    ],
    "names": "kjv",
    "language": "en",
    "librarian": [],
    "aliases": []
  }
}
''',
  'dictionaries_v1/strongshebrew/H0430.json': r'''{
  "schema": "getbible-dictionary-entry-v1",
  "dictionary": "strongshebrew",
  "language": "en",
  "id": "H0430",
  "key": "00430",
  "occurrence": 1,
  "aliases": [
    "H0430"
  ],
  "text": "God."
}
''',
  'dictionaries_v1/strongshebrew/index.json': r'''{
  "schema": "getbible-dictionary-index-v1",
  "dictionary": "strongshebrew",
  "language": "en",
  "name": "Hebrew lexicon",
  "entry_url_template": "{entry}.json",
  "entry_count": 1,
  "unique_key_count": 1,
  "entries": [
    {
      "id": "H0430",
      "key": "00430",
      "search": "00430",
      "aliases": [
        "H0430"
      ]
    }
  ]
}
''',
  'dictionaries_v1/strongshebrew/metadata.json': r'''{
  "schema": "getbible-dictionary-metadata-v1",
  "id": "strongshebrew",
  "module": "strongshebrew",
  "name": "Hebrew lexicon",
  "language": "en",
  "version": "1.0",
  "license": "Public Domain",
  "driver": "RawLD",
  "source_type": "dictionary",
  "entry_count": 1,
  "unique_key_count": 1,
  "strong_prefix": "H",
  "bytes": 1000,
  "index_url": "index.json",
  "entry_url_template": "{entry}.json",
  "source": "CrossWire SWORD",
  "source_module_url": "https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=strongshebrew",
  "text_source": "Fixture source",
  "copyright": "Public domain fixture",
  "copyright_holder": "",
  "copyright_contact": {
    "name": "",
    "email": "",
    "address": ""
  },
  "distribution_notes": "Fixture only",
  "about": "A study test fixture.",
  "conversion_note": "Converted to plain text.",
  "references": {
    "api": "getbible-v2",
    "versification": "KJV",
    "translations": [
      "kjv"
    ],
    "names": "kjv",
    "language": "en",
    "librarian": [],
    "aliases": []
  }
}
''',
  'dictionaries_v1/swedish/index.json': r'''{
  "schema": "getbible-dictionary-index-v1",
  "dictionary": "swedish",
  "language": "sv",
  "name": "Swedish dictionary",
  "entry_url_template": "{entry}.json",
  "entry_count": 1,
  "unique_key_count": 1,
  "entries": [
    {
      "id": "ord",
      "key": "Ord",
      "search": "ord",
      "aliases": [
        "Word"
      ]
    }
  ]
}
''',
  'dictionaries_v1/swedish/metadata.json': r'''{
  "schema": "getbible-dictionary-metadata-v1",
  "id": "swedish",
  "module": "swedish",
  "name": "Swedish dictionary",
  "language": "sv",
  "version": "1.0",
  "license": "Public Domain",
  "driver": "RawLD",
  "source_type": "dictionary",
  "entry_count": 1,
  "unique_key_count": 1,
  "strong_prefix": null,
  "bytes": 1000,
  "index_url": "index.json",
  "entry_url_template": "{entry}.json",
  "source": "CrossWire SWORD",
  "source_module_url": "https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=swedish",
  "text_source": "Fixture source",
  "copyright": "Public domain fixture",
  "copyright_holder": "",
  "copyright_contact": {
    "name": "",
    "email": "",
    "address": ""
  },
  "distribution_notes": "Fixture only",
  "about": "A study test fixture.",
  "conversion_note": "Converted to plain text.",
  "references": {
    "api": "getbible-v2",
    "versification": "KJV",
    "translations": [
      "kjv"
    ],
    "names": "kjv",
    "language": "en",
    "librarian": [],
    "aliases": []
  }
}
''',
  'dictionaries_v1/swedish/ord.json': r'''{
  "schema": "getbible-dictionary-entry-v1",
  "dictionary": "swedish",
  "language": "sv",
  "id": "ord",
  "key": "Ord",
  "occurrence": 1,
  "aliases": [
    "Word"
  ],
  "text": "Ett ord."
}
''',
  'offline_study_v1/bookmarks.json': r'''{
  "schema_version": 1,
  "topics": [
    {
      "id": "authority-of-the-bible",
      "name": "Authority of the Bible",
      "color": "#93c5fd",
      "aliases": [
        "Bible authority"
      ],
      "default": true,
      "verses": [
        [
          1,
          1,
          1
        ],
        [
          1,
          1,
          3
        ],
        [
          43,
          3,
          16
        ]
      ]
    },
    {
      "id": "faith",
      "name": "Faith",
      "color": "#22c55e",
      "aliases": [],
      "default": false,
      "verses": [
        [
          43,
          3,
          16
        ]
      ]
    }
  ],
  "locales": {
    "en": {
      "schema_version": 1,
      "locale": "en",
      "name": "English",
      "topics": {
        "authority-of-the-bible": "Authority of the Bible",
        "faith": "Faith"
      }
    },
    "af": {
      "schema_version": 1,
      "locale": "af",
      "name": "Afrikaans",
      "topics": {
        "authority-of-the-bible": "Gesag van die Bybel"
      }
    }
  }
}
''',
  'offline_study_v1/commentary.json': r'''{
  "schema": "getbible-commentary-v1",
  "commentary": "fixture",
  "language": "en",
  "name": "Fixture Commentary",
  "books": [
    {
      "schema": "getbible-commentary-book-v1",
      "commentary": "fixture",
      "language": "en",
      "book": 1,
      "name": "Genesis",
      "chapters": [
        {
          "schema": "getbible-commentary-chapter-v1",
          "commentary": "fixture",
          "language": "en",
          "book": 1,
          "name": "Genesis",
          "chapter": 0,
          "entries": [
            {
              "book": 1,
              "chapter": 0,
              "verse": 0,
              "text": "Book introduction.\n\nA second paragraph."
            }
          ]
        },
        {
          "schema": "getbible-commentary-chapter-v1",
          "commentary": "fixture",
          "language": "en",
          "book": 1,
          "name": "Genesis",
          "chapter": 1,
          "entries": [
            {
              "book": 1,
              "chapter": 1,
              "verse": 0,
              "text": "Chapter introduction."
            },
            {
              "book": 1,
              "chapter": 1,
              "verse": 3,
              "text": "First ranged comment.\n\n<b>Plain text stays plain.</b>",
              "verses": [
                3,
                4,
                5
              ],
              "osis": "Gen.1.3",
              "references": [
                {
                  "ref": "Genesis 1:1-2",
                  "osis": "Gen.1.1-Gen.1.2",
                  "book": 1,
                  "chapter": 1,
                  "verse": 1,
                  "verses": [
                    1,
                    2
                  ],
                  "text": "Gen. 1:1–2"
                },
                {
                  "ref": "John 1",
                  "osis": "John.1",
                  "book": 43,
                  "chapter": 1
                }
              ]
            },
            {
              "book": 1,
              "chapter": 1,
              "verse": 5,
              "text": "Second comment for the same verse.",
              "osis": "Gen.1.5"
            },
            {
              "book": 1,
              "chapter": 1,
              "verse": 8,
              "text": "Cross-chapter quotation.",
              "verses": [
                8,
                9
              ],
              "osis": "Gen.1.8",
              "references": [
                {
                  "ref": "Genesis 1:1-2",
                  "osis": "Gen.1.1-Gen.1.2",
                  "book": 1,
                  "chapter": 1,
                  "verse": 1,
                  "verses": [
                    1,
                    2
                  ],
                  "text": "Gen. 1:1–2"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "schema": "getbible-commentary-book-v1",
      "commentary": "fixture",
      "language": "en",
      "book": 43,
      "name": "John",
      "chapters": [
        {
          "schema": "getbible-commentary-chapter-v1",
          "commentary": "fixture",
          "language": "en",
          "book": 43,
          "name": "John",
          "chapter": 2,
          "entries": [
            {
              "book": 43,
              "chapter": 2,
              "verse": 1,
              "text": "John commentary."
            }
          ]
        }
      ]
    }
  ]
}
''',
  'offline_study_v1/dictionary.json': r'''{
  "schema": "getbible-dictionary-v1",
  "dictionary": "strongsgreek",
  "language": "en",
  "name": "Greek lexicon",
  "entries": [
    {
      "schema": "getbible-dictionary-entry-v1",
      "dictionary": "strongsgreek",
      "language": "en",
      "id": "G3056",
      "key": "λόγος",
      "occurrence": 1,
      "aliases": [
        "G3056",
        "Word"
      ],
      "text": "Word; speech.\n\nA second paragraph.",
      "see_also": [
        {
          "id": "G4487",
          "key": "ῥῆμα"
        }
      ],
      "references": [
        {
          "ref": "John 1:1",
          "osis": "John.1.1",
          "book": 43,
          "chapter": 1,
          "verse": 1,
          "text": "John 1:1"
        }
      ]
    },
    {
      "schema": "getbible-dictionary-entry-v1",
      "dictionary": "strongsgreek",
      "language": "en",
      "id": "G3056--2",
      "key": "λόγος",
      "occurrence": 2,
      "aliases": [
        "G3056",
        "Word"
      ],
      "text": "A distinct definition."
    },
    {
      "schema": "getbible-dictionary-entry-v1",
      "dictionary": "strongsgreek",
      "language": "en",
      "id": "G4487",
      "key": "ῥῆμα",
      "occurrence": 1,
      "aliases": [
        "G4487"
      ],
      "text": "A saying.",
      "backlinks": [
        {
          "id": "G3056",
          "key": "λόγος"
        }
      ]
    }
  ]
}
''',
  'public_topic_index.json': r'''{
  "schema_version": 1,
  "catalog_version": 1,
  "checksum": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "counts": {
    "topics": 2,
    "verses": 3,
    "locales": 2
  },
  "resources": {
    "topics": "topics.json",
    "topic": "topics/{id}.json",
    "chapter": "verses/{book}/{chapter}.json",
    "locales": "locales.json",
    "locale": "locales/{locale}.json",
    "all": "all.json",
    "catalog": "catalog.json",
    "checksums": "checksums.json"
  },
  "locales": [
    "en",
    "af"
  ]
}
''',
  'public_topic_live_authority.json': r'''{
  "schema_version": 1,
  "id": "authority-of-the-bible",
  "name": "Authority of the Bible",
  "color": "#93c5fd",
  "aliases": [],
  "default": true,
  "names": {
    "af": "Gesag van die Bybel",
    "ar": "سلطة الكتاب المقدس",
    "br": "Aotrouniezh ar Bibl",
    "ch": "I otdinariu na taotao gi i Biblia",
    "cs": "Autorita Bible",
    "da": "Bibelens autoritet",
    "de": "Autorität der Bibel",
    "el": "Η αυθεντία της Αγίας Γραφής",
    "en": "Authority of the Bible",
    "eo": "Aŭtoritato de la Biblio",
    "es": "Autoridad de la Biblia",
    "et": "Piibli autoriteet",
    "eu": "Bibliaren agintaritza",
    "fi": "Raamatun auktoriteetti",
    "fr": "Autorité de la Bible",
    "gd": "Ùghdarras a' Bhìobaill",
    "gv": "Pooar yn Vible",
    "hbo": "סמכות המקרא",
    "hr": "Autoritet Biblije",
    "hu": "A Biblia tekintélye",
    "hy": "Աստվածաշնչի հեղինակություն",
    "id": "Otoritas Alkitab",
    "it": "Autorità della Bibbia",
    "ja": "聖書の権威",
    "ko": "성경의 권위",
    "la": "Auctoritas Sacrae Scripturae",
    "lt": "Biblijos autoritetas",
    "lv": "Bībeles autoritāte",
    "mg": "Fahefana ao amin’ny Baiboly",
    "mi": "Mana o te Paipera",
    "mn": "Библийн эрх мэдэл",
    "my": "သမ္မာကျမ်းစာ၏အာဏာ",
    "nb": "Bibelens autoritet",
    "nd": "Igunya leBhayibheli",
    "nl": "Gezag van de Bijbel",
    "nn": "Autoriteten til Bibelen",
    "pl": "Autorytet Biblii",
    "prs": "صلاحیت کتاب مقدس",
    "pt": "Autoridade da Bíblia",
    "ro": "Autoritatea Bibliei",
    "ru": "Авторитет Библии",
    "sn": "Simba reBhaibheri",
    "sq": "Autoriteti i Biblës",
    "sr": "Ауторитет Библије",
    "sv": "Bibelns auktoritet",
    "sw": "Mamlaka ya Biblia",
    "th": "สิทธิอำนาจของพระคัมภีร์",
    "tl": "Awtoridad ng Bibliya",
    "tpi": "Atoriti bilong Baibel",
    "tr": "Kutsal Kitap'ın Yetkisi",
    "uk": "Авторитет Біблії",
    "vi": "Thẩm quyền của Kinh Thánh",
    "zh": "圣经的权威",
    "zh-hant": "聖經的權威"
  },
  "verses": [
    [5, 4, 2],
    [5, 12, 32],
    [11, 8, 56],
    [19, 19, 7],
    [19, 93, 5],
    [19, 111, 7],
    [19, 119, 152],
    [20, 13, 13],
    [20, 30, 5],
    [20, 30, 6],
    [23, 8, 20],
    [23, 40, 8],
    [23, 51, 16],
    [24, 36, 1],
    [24, 36, 2],
    [26, 1, 3],
    [26, 12, 25],
    [27, 9, 12],
    [40, 5, 17],
    [40, 5, 18],
    [40, 24, 35],
    [42, 1, 1],
    [42, 1, 2],
    [42, 1, 3],
    [42, 1, 4],
    [42, 21, 33],
    [43, 17, 17],
    [44, 1, 16],
    [44, 2, 42],
    [44, 28, 25],
    [45, 4, 16],
    [46, 14, 37],
    [46, 15, 1],
    [46, 15, 2],
    [46, 15, 3],
    [46, 15, 4],
    [46, 15, 5],
    [46, 15, 6],
    [46, 15, 7],
    [46, 15, 8],
    [53, 2, 15],
    [55, 3, 15],
    [55, 3, 16],
    [58, 1, 1],
    [58, 1, 2],
    [60, 1, 11],
    [60, 1, 12],
    [60, 1, 25],
    [61, 1, 15],
    [61, 1, 16],
    [61, 1, 17],
    [61, 1, 18],
    [61, 1, 19],
    [61, 1, 20],
    [61, 1, 21],
    [61, 3, 2],
    [61, 3, 15],
    [61, 3, 16],
    [66, 1, 1]
  ]
}
''',
  'public_topic_locales.json': r'''{
  "schema_version": 1,
  "locales": [
    {
      "code": "en",
      "name": "English",
      "topics": 2
    },
    {
      "code": "af",
      "name": "Afrikaans",
      "topics": 1
    }
  ]
}
''',
  'public_topic_names_af.json': r'''{
  "schema_version": 1,
  "locale": "af",
  "name": "Afrikaans",
  "topics": {
    "authority-of-the-bible": "Gesag van die Bybel"
  }
}
''',
  'public_topic_reverse.json': r'''{
  "schema_version": 1,
  "book": 1,
  "chapter": 1,
  "verses": {
    "1": [
      "authority-of-the-bible"
    ],
    "3": [
      "authority-of-the-bible"
    ]
  }
}
''',
  'public_topic_single.json': r'''{
  "schema_version": 1,
  "id": "authority-of-the-bible",
  "name": "Authority of the Bible",
  "color": "#93c5fd",
  "aliases": [
    "Bible authority"
  ],
  "default": true,
  "names": {
    "en": "Authority of the Bible",
    "af": "Gesag van die Bybel"
  },
  "verses": [
    [
      1,
      1,
      1
    ],
    [
      1,
      1,
      3
    ],
    [
      43,
      3,
      16
    ]
  ]
}
''',
  'public_topic_summaries.json': r'''{
  "schema_version": 1,
  "topics": [
    {
      "id": "authority-of-the-bible",
      "name": "Authority of the Bible",
      "color": "#93c5fd",
      "aliases": [
        "Bible authority"
      ],
      "default": true,
      "verses": 3
    },
    {
      "id": "hope",
      "name": "Hope",
      "color": "#0000ff",
      "aliases": [],
      "default": false,
      "verses": 0
    }
  ]
}
''',
  'service_envelopes.json': r'''{
  "dictionaries": {
    "schema": "getbible-dictionaries-catalog-v1",
    "version": 1,
    "generated_at": "2026-10-08T10:00:00Z",
    "base_url": "https://dictionaries.getbible.net/v1/",
    "metadata_url_template": "{dictionary}/metadata.json",
    "index_url_template": "{dictionary}/index.json",
    "dictionary_url_template": "{dictionary}.json",
    "entry_url_template": "{dictionary}/{entry}.json",
    "module_count": 1,
    "dictionaries": [
      {
        "id": "fixture-lexicon",
        "name": "Fixture lexicon",
        "language": "en",
        "license": "Public Domain",
        "entry_count": 0,
        "unique_key_count": 0,
        "strong_prefix": null,
        "bytes": 0
      }
    ]
  },
  "commentaries": {
    "schema": "getbible-commentaries-catalog-v1",
    "version": 1,
    "generated_at": "2026-10-08T10:00:00Z",
    "base_url": "https://commentaries.getbible.net/v1/",
    "metadata_url_template": "{commentary}/metadata.json",
    "books_url_template": "{commentary}/books.json",
    "commentary_url_template": "{commentary}.json",
    "book_url_template": "{commentary}/{book}.json",
    "chapter_url_template": "{commentary}/{book}/{chapter}.json",
    "module_count": 1,
    "commentaries": [
      {
        "id": "fixture-commentary",
        "name": "Fixture Commentary",
        "language": "en",
        "license": "Public Domain",
        "book_count": 0,
        "chapter_count": 0,
        "entry_count": 0,
        "bytes": 0
      }
    ]
  },
  "bookmarks": {
    "schema_version": 1,
    "topics": [
      {
        "id": "fixture-topic",
        "name": "Fixture Topic",
        "color": "#123456",
        "aliases": [],
        "default": false,
        "verses": 0
      }
    ]
  },
  "search": {
    "query": {
      "text": "faith hope",
      "kind": "search",
      "translation": {
        "translation": "Fixture Bible",
        "abbreviation": "tst",
        "lang": "en",
        "language": "English",
        "direction": "LTR",
        "encoding": "UTF-8"
      },
      "engine_version": 5,
      "total": 2,
      "returned": 2,
      "offset": 0,
      "limit": 2,
      "has_more": false,
      "sha": null
    },
    "results": {
      "tst_1_1": {
        "translation": "Fixture Bible",
        "abbreviation": "tst",
        "lang": "en",
        "language": "English",
        "direction": "LTR",
        "encoding": "UTF-8",
        "book_nr": 1,
        "book_name": "Fixture Book",
        "chapter": 1,
        "name": "Fixture Book 1",
        "ref": [
          "Fixture Book 1"
        ],
        "verses": [
          {
            "verse": 1,
            "name": "Fixture Book 1:1",
            "text": "First  \nverse.",
            "tokens": [],
            "spans": []
          }
        ]
      },
      "tst_2_3": {
        "translation": "Fixture Bible",
        "abbreviation": "tst",
        "lang": "en",
        "language": "English",
        "direction": "LTR",
        "encoding": "UTF-8",
        "book_nr": 2,
        "book_name": "Fixture Book",
        "chapter": 3,
        "name": "Fixture Book 3",
        "ref": [
          "Fixture Book 3"
        ],
        "verses": [
          {
            "verse": 8,
            "name": "Fixture Book 3:8",
            "text": "Second verse.",
            "tokens": [],
            "spans": []
          }
        ]
      }
    },
    "matches": [
      {
        "reference": "Fixture Book 3:8",
        "book_nr": 2,
        "chapter": 3,
        "verse": 8,
        "score": 2.5,
        "occurrences": 2,
        "terms": [
          "faith",
          "hope"
        ]
      },
      {
        "reference": "Fixture Book 1:1",
        "book_nr": 1,
        "chapter": 1,
        "verse": 1,
        "score": 1,
        "occurrences": 1,
        "terms": [
          "faith"
        ]
      }
    ]
  },
  "search_reference": {
    "query": {
      "text": "Fixture Book 1:1",
      "kind": "reference",
      "translation": "tst",
      "engine_version": 5,
      "total": 1,
      "returned": 1
    },
    "results": {
      "tst_1_1": {
        "translation": "Fixture Bible",
        "abbreviation": "tst",
        "lang": "en",
        "language": "English",
        "direction": "LTR",
        "encoding": "UTF-8",
        "book_nr": 1,
        "book_name": "Fixture Book",
        "chapter": 1,
        "name": "Fixture Book 1",
        "ref": [
          "Fixture Book 1"
        ],
        "verses": [
          {
            "verse": 1,
            "name": "Fixture Book 1:1",
            "text": "First verse.",
            "tokens": [],
            "spans": []
          }
        ]
      }
    },
    "matches": [
      {
        "reference": "Fixture Book 1:1",
        "book_nr": 1,
        "chapter": 1,
        "verse": 1
      }
    ]
  },
  "search_empty": {
    "query": {
      "text": "no matches",
      "kind": "search",
      "translation": "tst",
      "engine_version": 5,
      "total": 0,
      "returned": 0,
      "offset": 0,
      "limit": 20,
      "has_more": false,
      "sha": null
    },
    "results": {},
    "matches": []
  },
  "search_compact": {
    "query": {
      "text": "fixture",
      "kind": "search",
      "translation": {},
      "engine_version": 5,
      "total": 1,
      "returned": 1
    },
    "results": {
      "tst_101_1": {
        "book_nr": 101,
        "chapter": 1,
        "verses": [
          {
            "verse": 1,
            "text": "Introduction  \\n",
            "name": "Fixture 1:1"
          }
        ]
      }
    },
    "matches": [
      {
        "reference": "Fixture introduction",
        "book_nr": 101,
        "chapter": 1,
        "verse": 1
      }
    ]
  }
}
''',
};
