// Generated by tool/ui_locale_inventory.py. Do not edit by hand.
// Explicit native UI extensions; Scripture and user text are excluded.

const Map<String, String> nativeUiKeys = <String, String>{
  "0–100 intervening units; available with All words.":
      "native.0100InterveningUnitsAvailableWithAllWords",
  "0 results. Try different words or broader filters.":
      "native.0ResultsTryDifferentWordsOrBroaderFilters",
  "A backup marking group is invalid.": "native.aBackupMarkingGroupIsInvalid",
  "A backup marking has invalid coordinates or timestamps.":
      "native.aBackupMarkingHasInvalidCoordinatesOrTimestamps",
  "A backup marking refers to a missing group.":
      "native.aBackupMarkingRefersToAMissingGroup",
  "A backup marking refers to a missing marking group.":
      "native.aBackupMarkingRefersToAMissingMarkingGroup",
  "A backup verse note has invalid coordinates or timestamps.":
      "native.aBackupVerseNoteHasInvalidCoordinatesOrTimestamps",
  "A bookmark contains an invalid source.":
      "native.aBookmarkContainsAnInvalidSource",
  "A marking contains an invalid text range.":
      "native.aMarkingContainsAnInvalidTextRange",
  "A marking group contains an invalid color.":
      "native.aMarkingGroupContainsAnInvalidColor",
  "A notebook block is limited to 100,000 characters.":
      "native.aNotebookBlockIsLimitedTo100000Characters",
  "A notebook identity is invalid.": "native.aNotebookIdentityIsInvalid",
  "A notebook reference requires a valid Scripture verse and label.":
      "native.aNotebookReferenceRequiresAValidScriptureVerseAnd",
  "A notebook timestamp is invalid.": "native.aNotebookTimestampIsInvalid",
  "A private backup is limited to 64 MiB.":
      "native.aPrivateBackupIsLimitedTo64MiB",
  "A private setting contains an unsupported value.":
      "native.aPrivateSettingContainsAnUnsupportedValue",
  "A private topic copy refers to a missing group.":
      "native.aPrivateTopicCopyRefersToAMissingGroup",
  "A retained notebook draft has an invalid owner or base revision.":
      "native.aRetainedNotebookDraftHasAnInvalidOwnerOr",
  "A running download is protected. If its window closed unexpectedly, retry after two minutes.":
      "native.aRunningDownloadIsProtectedIfItsWindowClosed",
  "A scoped private preference key is invalid.":
      "native.aScopedPrivatePreferenceKeyIsInvalid",
  "A shared bookmark must cover a complete verse.":
      "native.aSharedBookmarkMustCoverACompleteVerse",
  "A topic choice must be true or false.":
      "native.aTopicChoiceMustBeTrueOrFalse",
  "Abbreviation": "native.abbreviation",
  "About": "native.about",
  "Add group": "native.addGroup",
  "Add note block": "native.addNoteBlock",
  "Add or edit verse note": "native.addOrEditVerseNote",
  "{added} new markings copied. Your private group is independent of public updates.":
      "native.addedNewMarkingsCopiedYourPrivateGroupIsIndependent",
  "Additional recovered drafts from another editor:":
      "native.additionalRecoveredDraftsFromAnotherEditor",
  "Advanced filters": "native.advancedFilters",
  "All discovered books": "native.allDiscoveredBooks",
  "All resources": "native.allResources",
  "An introduction citation has no Scripture verse to preview.":
      "native.anIntroductionCitationHasNoScriptureVerseToPreview",
  "An update temporarily needs space for both versions. The previous installation remains readable until every file is verified.":
      "native.anUpdateTemporarilyNeedsSpaceForBothVersionsThe",
  "Another file operation is already open.":
      "native.anotherFileOperationIsAlreadyOpen",
  "Appearance": "native.appearance",
  "Apply": "native.apply",
  "Autosaves locally. Ctrl/⌘ + Enter saves immediately.":
      "native.autosavesLocallyCtrlEnterSavesImmediately",
  "Available resources": "native.availableResources",
  "Back to verse": "native.backToVerse",
  "Backup and restore": "native.backupAndRestore",
  "Baskerville": "native.baskerville",
  "Bible": "native.bible",
  "Bibles download in full when you open them. Dictionaries and commentaries download automatically unless you turn off Keep offline. The complete bookmark dataset downloads only when you choose Install.":
      "native.biblesDownloadInFullWhenYouOpenThemDictionaries",
  "Block {position}": "native.blockPosition",
  "{blockCount} block(s)": "native.blockcountBlockS",
  "Book {book}": "native.bookBook",
  "Book introduction": "native.bookIntroduction",
  "Book {number}": "native.bookNumber",
  "Bookmark topics": "native.bookmarkTopics",
  "Browse all dictionaries": "native.browseAllDictionaries",
  "Browse catalogue": "native.browseCatalogue",
  "Cambria": "native.cambria",
  "Cancel download": "native.cancelDownload",
  "Cancel edit": "native.cancelEdit",
  "Cancel import": "native.cancelImport",
  "Case sensitive": "native.caseSensitive",
  "Catalog subject": "native.catalogSubject",
  "Chapter {chapter} · verse {verses}": "native.chapterChapterVerseVerses",
  "Chapter {chapter} · verses {verses}": "native.chapterChapterVersesVerses",
  "Chapter introduction": "native.chapterIntroduction",
  "Charter": "native.charter",
  "Check dictionaries again": "native.checkDictionariesAgain",
  "Check for updates": "native.checkForUpdates",
  "Checking dictionary definitions": "native.checkingDictionaryDefinitions",
  "Checking or transferring private data":
      "native.checkingOrTransferringPrivateData",
  "Checking published integrity manifest":
      "native.checkingPublishedIntegrityManifest",
  "Choose a commentary": "native.chooseACommentary",
  "Choose a marking": "native.chooseAMarking",
  "Choose a notebook": "native.chooseANotebook",
  "Choose a resource": "native.chooseAResource",
  "Choose a UTF-8 JSON backup up to 64 MiB. The entire file is checked before you confirm. Import merges saved data and keeps unrelated records; conflicting notebooks are preserved as separate copies.":
      "native.chooseAUTF8JSONBackupUpTo64",
  "Choose backup file": "native.chooseBackupFile",
  "Choose marking for {reference}": "native.chooseMarkingForReference",
  "Citation provenance: {api} · {versification}":
      "native.citationProvenanceApiVersification",
  "Citations were resolved by {api} ({versification}). Preview requests use {bible}; availability and versification may differ.":
      "native.citationsWereResolvedByApiVersificationPreviewRequestsUse",
  "Clear downloads": "native.clearDownloads",
  "Clear downloads?": "native.clearDownloadse81a1da9",
  "Close": "native.close",
  "Close marking groups": "native.closeMarkingGroups",
  "Close offline resources": "native.closeOfflineResources",
  "Close reference preview": "native.closeReferencePreview",
  "Close Study tools": "native.closeStudyTools",
  "Color": "native.color",
  "Comma-separated; at most 32 terms, 100 characters each.":
      "native.commaSeparatedAtMost32Terms100CharactersEach",
  "Commentary resource": "native.commentaryResource",
  "Complete private backup": "native.completePrivateBackup",
  "Complete private backup preview": "native.completePrivateBackupPreview",
  "Confirm import": "native.confirmImport",
  "Copy failed; retry is safe. {copyError}":
      "native.copyFailedRetryIsSafeCopyError",
  "Copy markings": "native.copyMarkings",
  "Copy or share Scripture": "native.copyOrShareScripture",
  "Copy public topic to my markings?": "native.copyPublicTopicToMyMarkings",
  "Copy to my markings": "native.copyToMyMarkings",
  "Copying…": "native.copying",
  "Could not load this verse. Try again.":
      "native.couldNotLoadThisVerseTryAgain",
  "Could not prepare the copy. {error}": "native.couldNotPrepareTheCopyError",
  "Could not save or restore your topic choices. {preferenceError}":
      "native.couldNotSaveOrRestoreYourTopicChoicesPreferenceError",
  "Could not update bookmarks. {error}": "native.couldNotUpdateBookmarksError",
  "{count} bookmarks": "native.countBookmarks",
  "{count} dictionaries could not be checked. Showing confirmed definitions.":
      "native.countDictionariesCouldNotBeCheckedShowingConfirmedDefinitions",
  "{count} downloads waiting": "native.countDownloadsWaiting",
  "{count} indexed definition": "native.countIndexedDefinition",
  "{count} indexed definitions": "native.countIndexedDefinitions",
  "{count} of 83 available selections": "native.countOf83AvailableSelections",
  "{count} selected books": "native.countSelectedBooks",
  "{count} verses in the resolved reference. Full-text filters do not apply.":
      "native.countVersesInTheResolvedReferenceFullTextFilters",
  "Create a notebook for your study notes or sermon outline.":
      "native.createANotebookForYourStudyNotesOrSermon",
  "Dark reading palette": "native.darkReadingPalette",
  "Delete marking group?": "native.deleteMarkingGroup",
  "Delete {name}": "native.deleteName",
  "Delete note": "native.deleteNote",
  "Delete note block": "native.deleteNoteBlock",
  "Delete note block?": "native.deleteNoteBlock3ead4f56",
  "Delete notebook": "native.deleteNotebook",
  "Delete notebook?": "native.deleteNotebook68e214b1",
  "Deuterocanon": "native.deuterocanon",
  "Diacritics": "native.diacritics",
  "Dictionaries with definitions ({count})":
      "native.dictionariesWithDefinitionsCount",
  "Dictionary": "native.dictionary",
  "Dictionary attribution": "native.dictionaryAttribution",
  "“{displayTitle}” and its blocks will be permanently deleted from this device.":
      "native.displaytitleAndItsBlocksWillBePermanentlyDeletedFrom",
  "Download all global bookmarks": "native.downloadAllGlobalBookmarks",
  "Download global bookmarks": "native.downloadGlobalBookmarks",
  "Download requested. Check your browser downloads to keep the file.":
      "native.downloadRequestedCheckYourBrowserDownloadsToKeepThe",
  "Download size not published": "native.downloadSizeNotPublished",
  "Download this topic’s global bookmarks":
      "native.downloadThisTopicSGlobalBookmarks",
  "Downloading {name}": "native.downloadingName",
  "Downloading the complete Bible": "native.downloadingTheCompleteBible",
  "Enter a reference to preview Scripture in your selected Bible.":
      "native.enterAReferenceToPreviewScriptureInYourSelected",
  "Enter a word to search this dictionary’s index.":
      "native.enterAWordToSearchThisDictionarySIndex",
  "Enter words or a Scripture reference. Search uses the selected Bible online.":
      "native.enterWordsOrAScriptureReferenceSearchUsesThe",
  "Estimated download: {estimatedBytes}":
      "native.estimatedDownloadEstimatedBytes",
  "Estimated download: {estimatedBytes}.":
      "native.estimatedDownloadEstimatedBytes2eec27e9",
  "Exact diacritics": "native.exactDiacritics",
  "Export in progress": "native.exportInProgress",
  "Export notebook Markdown": "native.exportNotebookMarkdown",
  "{exportLabel} ready. Save the file to keep this snapshot.":
      "native.exportlabelReadySaveTheFileToKeepThisSnapshot",
  "File access is unavailable. Copy the text instead.":
      "native.fileAccessIsUnavailableCopyTheTextInstead",
  "File saved.": "native.fileSaved",
  "File selection cancelled.": "native.fileSelectionCancelled",
  "Find a book": "native.findABook",
  "Find a dictionary word": "native.findADictionaryWord",
  "Find a resource": "native.findAResource",
  "Fold diacritics": "native.foldDiacritics",
  "Follow": "native.follow",
  "Followed": "native.followed",
  "G": "native.g",
  "Garamond": "native.garamond",
  "getBible": "native.getbible",
  "getBible — {wordsOfEternalLife}": "native.getbibleWordsOfEternalLife",
  "Global bookmarks": "native.globalBookmarks",
  "Global topics could not be updated. Your saved bookmarks are still available. {error}":
      "native.globalTopicsCouldNotBeUpdatedYourSavedBookmarks",
  "Gloss": "native.gloss",
  "Group name": "native.groupName",
  "{groupName}\n\n{newAssociationCount} new whole-verse markings; {alreadyPresent} already present.\n\nThis creates or adds to your independent private copy. Existing groups, notes and markings stay intact. Only canonical coordinates and the public topic color are copied; Scripture text is not downloaded. Public changes will not edit or delete your copy.":
      "native.groupnameNewAssociationCountNewWholeVerseMarkingsAlreadyPresentAlreadyPresent",
  "{groups} groups, {markings} markings, {notes} verse notes, {notebooks} notebooks, {drafts} drafts, {settings} private settings.":
      "native.groupsGroupsMarkingsMarkingsNotesVerseNotesNotebooksNotebooks",
  "Hide topic": "native.hideTopic",
  "High contrast": "native.highContrast",
  "History — {key}": "native.historyKey",
  "{id} · definition {count}": "native.idDefinitionCount",
  "{id} · {language} · definition {count}": "native.idLanguageDefinitionCount",
  "Import complete: {groupsAdded} groups added, {markingsAdded} markings added, {notesChanged} verse notes updated, {notebooksAdded} notebooks added, {draftsAdded} drafts added, {notebookConflicts} notebook conflicts preserved, {settingsRestored} preferences restored.":
      "native.importCompleteGroupsAddedGroupsAddedMarkingsAddedMarkingsAddedNotesChanged",
  "Include online dictionaries": "native.includeOnlineDictionaries",
  "Include this quotation": "native.includeThisQuotation",
  "Indexing {name}": "native.indexingName",
  "Insert": "native.insert",
  "Insert current Scripture": "native.insertCurrentScripture",
  "Insert Scripture": "native.insertScripture",
  "Install": "native.install",
  "Install {title}?": "native.installTitle",
  "Installed": "native.installed",
  "Installed Bible (offline)": "native.installedBibleOffline",
  "Installed on this device · available offline":
      "native.installedOnThisDeviceAvailableOffline",
  "Introduction": "native.introduction",
  "Introduction citation unavailable": "native.introductionCitationUnavailable",
  "Invalid alternate topic copy provenance.":
      "native.invalidAlternateTopicCopyProvenance",
  "Invalid bookmark source scope.": "native.invalidBookmarkSourceScope",
  "Invalid recent bookmark topics.": "native.invalidRecentBookmarkTopics",
  "Invalid topic copy provenance.": "native.invalidTopicCopyProvenance",
  "Keep offline": "native.keepOffline",
  "Keep your own backup of saved Scripture, verse notes, notebooks, drafts and preferences. Backups contain private text. Choose where you save them and who can access them.":
      "native.keepYourOwnBackupOfSavedScriptureVerseNotes",
  "{label} · {bytes} saved": "native.labelBytesSaved",
  "Lemma": "native.lemma",
  "{length} canonical verse associations · Public getBible Bookmarks v1":
      "native.lengthCanonicalVerseAssociationsPublicGetBibleBookmarksV1",
  "{length} notebook(s)": "native.lengthNotebookS",
  "License and copyright": "native.licenseAndCopyright",
  "Light reading palette": "native.lightReadingPalette",
  "Linked from": "native.linkedFrom",
  "{loaded} of {total} results loaded.": "native.loadedOfTotalResultsLoaded",
  "Loading commentary": "native.loadingCommentary",
  "Loading dictionary": "native.loadingDictionary",
  "Loading more matches": "native.loadingMoreMatches",
  "Loading reference": "native.loadingReference",
  "Loading verse…": "native.loadingVerse",
  "Local storage is unavailable": "native.localStorageIsUnavailable",
  "Look up": "native.lookUp",
  "{lovinglyMaintainedBy} Vast Development Method":
      "native.lovinglymaintainedbyVastDevelopmentMethod",
  "Manage groups": "native.manageGroups",
  "Mark: {name}": "native.markName",
  "Match mode": "native.matchMode",
  "More marking groups…": "native.moreMarkingGroups",
  "More matches exist beyond the page offset limit. Narrow the search using books, scope or additional words.":
      "native.moreMatchesExistBeyondThePageOffsetLimitNarrow",
  "Morphology": "native.morphology",
  "Move block down": "native.moveBlockDown",
  "Move block up": "native.moveBlockUp",
  "My markings": "native.myMarkings",
  "New notebook": "native.newNotebook",
  "No commentary in this Bible’s language is selected. Choose an available resource explicitly; its source language will be shown.":
      "native.noCommentaryInThisBibleSLanguageIsSelected",
  "No complete resources saved yet. Automatic downloads will continue when a connection is available.":
      "native.noCompleteResourcesSavedYetAutomaticDownloadsWillContinue",
  "No dictionary resources are currently published.":
      "native.noDictionaryResourcesAreCurrentlyPublished",
  "No exact definition could be confirmed for this selection.":
      "native.noExactDefinitionCouldBeConfirmedForThisSelection",
  "No exact definition could be confirmed in the installed dictionaries.":
      "native.noExactDefinitionCouldBeConfirmedInTheInstalled",
  "No marking groups match this search.":
      "native.noMarkingGroupsMatchThisSearch",
  "No matching resources.": "native.noMatchingResources",
  "No topics match these choices. A verse with no public associations is valid.":
      "native.noTopicsMatchTheseChoicesAVerseWithNo",
  "Not yet available offline": "native.notYetAvailableOffline",
  "NOTE": "native.note",
  "Notebook title": "native.notebookTitle",
  "Notebooks": "native.notebooks",
  "Notes about this Scripture": "native.notesAboutThisScripture",
  "Offline cached Scripture — verification unavailable":
      "native.offlineCachedScriptureVerificationUnavailable",
  "Offline search uses exact diacritics and Bible order. Folding, relevance, proximity and Deuterocanon scope require Online search. Choose individual books to include other offline scopes. Install the selected Bible in Offline resources first.":
      "native.offlineSearchUsesExactDiacriticsAndBibleOrderFolding",
  "Online search": "native.onlineSearch",
  "Open in reader": "native.openInReader",
  "Open {reference}": "native.openReference",
  "Open reference preview": "native.openReferencePreview",
  "Open saved topic": "native.openSavedTopic",
  "Opening local data": "native.openingLocalData",
  "Personal bookmarks, topic names, colors, notes and notebooks will remain saved.":
      "native.personalBookmarksTopicNamesColorsNotesAndNotebooksWill",
  "Personal notebooks": "native.personalNotebooks",
  "Prepare complete backup": "native.prepareCompleteBackup",
  "Prepare website backup": "native.prepareWebsiteBackup",
  "Preparing download": "native.preparingDownload",
  "Preview": "native.preview",
  "Preview {reference}": "native.previewReference",
  "Preview shortened. The saved file includes the complete notebook.":
      "native.previewShortenedTheSavedFileIncludesTheCompleteNotebook",
  "Previous citation": "native.previousCitation",
  "Previous dictionary word": "native.previousDictionaryWord",
  "Private data": "native.privateData",
  "Proximity (optional)": "native.proximityOptional",
  "Public topics": "native.publicTopics",
  "Public topics · {label}": "native.publicTopicsLabel",
  "Readable Markdown for saving or sharing. Use Complete private backup for a restorable copy.":
      "native.readableMarkdownForSavingOrSharingUseCompletePrivate",
  "Reduce motion": "native.reduceMotion",
  "Reference": "native.reference",
  "Reference preview": "native.referencePreview",
  "Refresh download status": "native.refreshDownloadStatus",
  "Related entries": "native.relatedEntries",
  "Related ({length})": "native.relatedLength",
  "Relevance order": "native.relevanceOrder",
  "Remove all personal verse markings": "native.removeAllPersonalVerseMarkings",
  "Remove download": "native.removeDownload",
  "Remove downloaded global bookmarks?":
      "native.removeDownloadedGlobalBookmarks",
  "Remove from {name}": "native.removeFromName",
  "Remove global bookmark": "native.removeGlobalBookmark",
  "Remove global bookmark?": "native.removeGlobalBookmarkf268dfa8",
  "Remove global bookmarks": "native.removeGlobalBookmarks",
  "Remove highlighting": "native.removeHighlighting",
  "Remove personal bookmark": "native.removePersonalBookmark",
  "Remove personal bookmark?": "native.removePersonalBookmark99fce65b",
  "Remove this membership at {reference}? Other topics and the other origin remain saved.":
      "native.removeThisMembershipAtReferenceOtherTopicsAndThe",
  "Remove this topic’s global bookmarks":
      "native.removeThisTopicSGlobalBookmarks",
  "Remove {title}?": "native.removeTitle",
  "Resource choices could not refresh. Reopen the reader to retry.":
      "native.resourceChoicesCouldNotRefreshReopenTheReaderTo",
  "Resource type": "native.resourceType",
  "Restart search": "native.restartSearch",
  "Restore a backup": "native.restoreABackup",
  "Restoring local topic choices…": "native.restoringLocalTopicChoices",
  "Retained locally; the saved notebook is unchanged.":
      "native.retainedLocallyTheSavedNotebookIsUnchanged",
  "Retry dictionary": "native.retryDictionary",
  "Retry download": "native.retryDownload",
  "Return to {reference} before changing this retained verse-note draft.":
      "native.returnToReferenceBeforeChangingThisRetainedVerseNote",
  "Save as new notebook": "native.saveAsNewNotebook",
  "Save cancelled.": "native.saveCancelled",
  "Save draft as new notebook": "native.saveDraftAsNewNotebook",
  "Save file": "native.saveFile",
  "Save group": "native.saveGroup",
  "Save now": "native.saveNow",
  "Save or close the note editor before opening another reference.":
      "native.saveOrCloseTheNoteEditorBeforeOpeningAnother",
  "Save or close the verse note before backing up or importing private data.":
      "native.saveOrCloseTheVerseNoteBeforeBackingUp",
  "Save or close the verse note before changing the passage. Passage controls are temporarily unavailable.":
      "native.saveOrCloseTheVerseNoteBeforeChangingThe",
  "Save or close the verse note before closing the application.":
      "native.saveOrCloseTheVerseNoteBeforeClosingThe",
  "Save or close the verse note before opening another passage.":
      "native.saveOrCloseTheVerseNoteBeforeOpeningAnother",
  "Save or retry your notebook draft before exporting.":
      "native.saveOrRetryYourNotebookDraftBeforeExporting",
  "Saved legacy Scripture (API v2). Connect to refresh this passage from v3.":
      "native.savedLegacyScriptureAPIV2ConnectToRefreshThis",
  "Saved locally": "native.savedLocally",
  "Saved Scripture": "native.savedScripture",
  "Saved selection · {translation}": "native.savedSelectionTranslation",
  "Saving…": "native.saving",
  "Saving is unavailable. Copy the text instead.":
      "native.savingIsUnavailableCopyTheTextInstead",
  "Scripture citations": "native.scriptureCitations",
  "Scripture copied": "native.scriptureCopied",
  "Scripture reference": "native.scriptureReference",
  "Search {bible}": "native.searchBible",
  "Search only the selected installed Bible. No query is sent online.":
      "native.searchOnlyTheSelectedInstalledBibleNoQueryIs",
  "Search scope": "native.searchScope",
  "Search selected books": "native.searchSelectedBooks",
  "Search selected phrase": "native.searchSelectedPhrase",
  "Search selected text": "native.searchSelectedText",
  "Search selection": "native.searchSelection",
  "Search source": "native.searchSource",
  "Search {toUpperCase}": "native.searchToUpperCase",
  "Searching installed dictionaries.": "native.searchingInstalledDictionaries",
  "Searching Scripture": "native.searchingScripture",
  "See also": "native.seeAlso",
  "Share": "native.share",
  "Share cancelled.": "native.shareCancelled",
  "Share completed.": "native.shareCompleted",
  "Share sheet opened. Choose an app to finish sharing.":
      "native.shareSheetOpenedChooseAnAppToFinishSharing",
  "Share text": "native.shareText",
  "Sharing could not be completed. Save or copy the text instead.":
      "native.sharingCouldNotBeCompletedSaveOrCopyThe",
  "Sharing is unavailable here. Save or copy the text instead.":
      "native.sharingIsUnavailableHereSaveOrCopyTheText",
  "Show emphasis provided by this Bible edition":
      "native.showEmphasisProvidedByThisBibleEdition",
  "Show hidden": "native.showHidden",
  "Show more dictionary words": "native.showMoreDictionaryWords",
  "Show more verses": "native.showMoreVerses",
  "Show topic": "native.showTopic",
  "Showing the first 100 resources. Narrow your search to find more.":
      "native.showingTheFirst100ResourcesNarrowYourSearchTo",
  "Six-digit hex color, for example {example}":
      "native.sixDigitHexColorForExampleExample",
  "Source annotation": "native.sourceAnnotation",
  "Source: {name} · {language}": "native.sourceNameLanguage",
  "Source note": "native.sourceNote",
  "Source text styles": "native.sourceTextStyles",
  "Source type": "native.sourceType",
  "Source variant": "native.sourceVariant",
  "Speaker": "native.speaker",
  "Study and sermon notes stay on this device. Verse notes remain inline under Scripture.":
      "native.studyAndSermonNotesStayOnThisDeviceVerse",
  "Study or sermon notes": "native.studyOrSermonNotes",
  "Study resource": "native.studyResource",
  "Study selected word": "native.studySelectedWord",
  "Text and JSON files": "native.textAndJSONFiles",
  "Text copied.": "native.textCopied",
  "The app could not open its local data. Check available storage and browser permissions, then retry. Do not clear site data to fix this error.":
      "native.theAppCouldNotOpenItsLocalDataCheck",
  "The backup contains an invalid private setting.":
      "native.theBackupContainsAnInvalidPrivateSetting",
  "The backup contains duplicate canonical verse notes.":
      "native.theBackupContainsDuplicateCanonicalVerseNotes",
  "The backup contains duplicate draft journals.":
      "native.theBackupContainsDuplicateDraftJournals",
  "The backup contains duplicate marking group IDs.":
      "native.theBackupContainsDuplicateMarkingGroupIDs",
  "The backup contains duplicate marking groups.":
      "native.theBackupContainsDuplicateMarkingGroups",
  "The backup contains duplicate markings.":
      "native.theBackupContainsDuplicateMarkings",
  "The backup contains duplicate notebook blocks.":
      "native.theBackupContainsDuplicateNotebookBlocks",
  "The backup contains duplicate notebooks.":
      "native.theBackupContainsDuplicateNotebooks",
  "The backup contains duplicate settings.":
      "native.theBackupContainsDuplicateSettings",
  "The backup contains duplicate verse notes.":
      "native.theBackupContainsDuplicateVerseNotes",
  "The backup could not be opened. Please try again.":
      "native.theBackupCouldNotBeOpenedPleaseTryAgain",
  "The backup exceeds 100,000 private records.":
      "native.theBackupExceeds100000PrivateRecords",
  "The backup was imported. Reopen the reader to refresh its saved data.":
      "native.theBackupWasImportedReopenTheReaderToRefresh",
  "The book introduction could not be loaded. Chapter commentary remains available.":
      "native.theBookIntroductionCouldNotBeLoadedChapterCommentary",
  "The commentary choice was not saved. Select it again to retry.":
      "native.theCommentaryChoiceWasNotSavedSelectItAgain",
  "The complete backup exceeds the 64 MiB file limit.":
      "native.theCompleteBackupExceedsThe64MiBFileLimit",
  "The daily passage could not be opened. {error}":
      "native.theDailyPassageCouldNotBeOpenedError",
  "The export filename is invalid.": "native.theExportFilenameIsInvalid",
  "The file operation could not be completed.":
      "native.theFileOperationCouldNotBeCompleted",
  "The file operation was interrupted. Please retry.":
      "native.theFileOperationWasInterruptedPleaseRetry",
  "The latest notebook changes could not be saved. Return to Notebooks and retry before closing.":
      "native.theLatestNotebookChangesCouldNotBeSavedReturn",
  "The latest private changes could not be saved. Retry saving before closing.":
      "native.theLatestPrivateChangesCouldNotBeSavedRetry",
  "The lookup limit was reached. Try a more specific word.":
      "native.theLookupLimitWasReachedTryAMoreSpecific",
  "The note could not be saved. Your draft is kept. {error}":
      "native.theNoteCouldNotBeSavedYourDraftIs",
  "The notebook could not be exported. Your private draft remains available.":
      "native.theNotebookCouldNotBeExportedYourPrivateDraft",
  "The notebook could not be saved or loaded. Your open draft is retained. {error}":
      "native.theNotebookCouldNotBeSavedOrLoadedYour",
  "The notebook exceeds its document limits or contains duplicate block identities.":
      "native.theNotebookExceedsItsDocumentLimitsOrContainsDuplicate",
  "The offline preparation queue is full. Retry after current downloads finish.":
      "native.theOfflinePreparationQueueIsFullRetryAfterCurrent",
  "The operation could not be completed. Please try another option.":
      "native.theOperationCouldNotBeCompletedPleaseTryAnother",
  "The passage could not be opened. Your notebook draft is retained. {error}":
      "native.thePassageCouldNotBeOpenedYourNotebookDraft",
  "The private data operation failed. Your saved data remains available. Please retry.":
      "native.thePrivateDataOperationFailedYourSavedDataRemains",
  "The private preference value is invalid.":
      "native.thePrivatePreferenceValueIsInvalid",
  "The reference could not be opened. {error}":
      "native.theReferenceCouldNotBeOpenedError",
  "The resource choice could not be saved on this device. The dictionary remains available.":
      "native.theResourceChoiceCouldNotBeSavedOnThis",
  "The saved commentary choice could not be read.":
      "native.theSavedCommentaryChoiceCouldNotBeRead",
  "The saved reading position is invalid.":
      "native.theSavedReadingPositionIsInvalid",
  "The selected file exceeds the size limit.":
      "native.theSelectedFileExceedsTheSizeLimit",
  "The selected file is not a valid getBible backup.":
      "native.theSelectedFileIsNotAValidGetBibleBackup",
  "The selected file is not valid UTF-8 text.":
      "native.theSelectedFileIsNotValidUTF8Text",
  "The selected notebook is absent from the backup.":
      "native.theSelectedNotebookIsAbsentFromTheBackup",
  "The selected verse could not be opened.":
      "native.theSelectedVerseCouldNotBeOpened",
  "The service requested a pause before retrying.":
      "native.theServiceRequestedAPauseBeforeRetrying",
  "The source does not publish a download size.":
      "native.theSourceDoesNotPublishADownloadSize",
  "The text exceeds the size limit.": "native.theTextExceedsTheSizeLimit",
  "This backup contains bookmarks from another provider. Export a complete private backup to preserve their source.":
      "native.thisBackupContainsBookmarksFromAnotherProviderExportA",
  "This chapter has no commentary covering verse {verse}. Try Whole chapter to read its other material.":
      "native.thisChapterHasNoCommentaryCoveringVerseVerseTry",
  "This chapter was checked against the hash published by getBible and matches the current source.":
      "native.thisChapterWasCheckedAgainstTheHashPublishedBy",
  "This complete backup format is not supported.":
      "native.thisCompleteBackupFormatIsNotSupported",
  "This edit exceeds the note block or notebook size limit. Shorten this block or another block before continuing.":
      "native.thisEditExceedsTheNoteBlockOrNotebookSize",
  "This edit exceeds the title or notebook size limit. Shorten the text before continuing.":
      "native.thisEditExceedsTheTitleOrNotebookSizeLimit",
  "This format does not contain notebooks or drafts.":
      "native.thisFormatDoesNotContainNotebooksOrDrafts",
  "This getBible backup version is not supported.":
      "native.thisGetBibleBackupVersionIsNotSupported",
  "This is the last known good copy saved on this device. It remains readable offline, but the current source hash could not be checked.":
      "native.thisIsTheLastKnownGoodCopySavedOn",
  "This notebook format is unsupported.":
      "native.thisNotebookFormatIsUnsupported",
  "This passage changed. Reopen its bookmark menu.":
      "native.thisPassageChangedReopenItsBookmarkMenu",
  "This passage is unavailable in the selected Bible.":
      "native.thisPassageIsUnavailableInTheSelectedBible",
  "This permanently deletes this block from the notebook.":
      "native.thisPermanentlyDeletesThisBlockFromTheNotebook",
  "This published chapter contains no commentary entries.":
      "native.thisPublishedChapterContainsNoCommentaryEntries",
  "This reference or translation is unavailable.":
      "native.thisReferenceOrTranslationIsUnavailable",
  "This removes only the installed public resource and its search index. Your notes, notebooks, copied markings and preferences are preserved.":
      "native.thisRemovesOnlyTheInstalledPublicResourceAndIts",
  "This removes public downloads and cached content. Your notes, notebooks, bookmarks and download choices remain. Bibles download again when opened; enabled dictionaries and commentaries return on next use or startup. The complete bookmark dataset stays removed until you choose to install it again.":
      "native.thisRemovesPublicDownloadsAndCachedContentYourNotes",
  "This resource belongs to another source.":
      "native.thisResourceBelongsToAnotherSource",
  "This resource has no published commentary for {reference}.":
      "native.thisResourceHasNoPublishedCommentaryForReference",
  "This resource is in {sourceLanguage}; your Bible is in {bibleLanguage}.":
      "native.thisResourceIsInSourceLanguageYourBibleIsIn",
  "This search result is unavailable in the selected Bible.":
      "native.thisSearchResultIsUnavailableInTheSelectedBible",
  "This text is too large for a share sheet. Save it as a file instead.":
      "native.thisTextIsTooLargeForAShareSheet",
  "This topic has no verse associations.":
      "native.thisTopicHasNoVerseAssociations",
  "This verse is unavailable in the selected Bible.":
      "native.thisVerseIsUnavailableInTheSelectedBible",
  "Times New Roman": "native.timesNewRoman",
  "Too many drafts.": "native.tooManyDrafts",
  "Too many notebooks.": "native.tooManyNotebooks",
  "Too many settings.": "native.tooManySettings",
  "Topic color {color}": "native.topicColorColor",
  "Topic name language": "native.topicNameLanguage",
  "Topics": "native.topics",
  "Translation source": "native.translationSource",
  "Transliteration": "native.transliteration",
  "Turning this off removes the downloaded copy and stops automatic downloads for this resource.":
      "native.turningThisOffRemovesTheDownloadedCopyAndStops",
  "Unable to load this reference. Check your connection and try again.":
      "native.unableToLoadThisReferenceCheckYourConnectionAnd",
  "Unfollow": "native.unfollow",
  "Unlocated source word": "native.unlocatedSourceWord",
  "{unsavedCount} other notebook draft(s) need saving.":
      "native.unsavedcountOtherNotebookDraftSNeedSaving",
  "Unsupported reader preferences.": "native.unsupportedReaderPreferences",
  "Update / verify": "native.updateVerify",
  "Use Complete private backup to save notebooks and retained drafts. Website-compatible backups contain verse notes and markings only.":
      "native.useCompletePrivateBackupToSaveNotebooksAndRetained",
  "{usedBytes} of {quotaBytes} offline content budget used. Device or browser storage may have a lower limit.":
      "native.usedbytesOfQuotaBytesOfflineContentBudgetUsedDeviceOr",
  "Using English names. {localeError}": "native.usingEnglishNamesLocaleError",
  "Validating and indexing Scripture": "native.validatingAndIndexingScripture",
  "Verified cached Scripture": "native.verifiedCachedScripture",
  "Verified {name}": "native.verifiedName",
  "Verified Scripture": "native.verifiedScripture",
  "Verified source revision: {revision}":
      "native.verifiedSourceRevisionRevision",
  "Verse commentary": "native.verseCommentary",
  "Verse topics": "native.verseTopics",
  "{verseCount} verse associations{here}":
      "native.versecountVerseAssociationsHere",
  "Verses {firstVerse}–{lastVerse}": "native.versesFirstVerseLastVerse",
  "Verses use your selected Bible. Missing verses are shown as unavailable.":
      "native.versesUseYourSelectedBibleMissingVersesAreShown",
  "Verses {verses}": "native.versesVerses",
  "Version": "native.version",
  "Version date": "native.versionDate",
  "Wait for the passage to finish opening before editing a verse note.":
      "native.waitForThePassageToFinishOpeningBeforeEditing",
  "Website backup preview": "native.websiteBackupPreview",
  "Website backups include saved groups, markings, verse notes and reader preferences. They do not include notebooks, drafts or additional private settings. Downloaded study and Bible resources are not included in either format.":
      "native.websiteBackupsIncludeSavedGroupsMarkingsVerseNotesAnd",
  "Website-compatible backup": "native.websiteCompatibleBackup",
  "While the app is open, saved resources are checked for updates every 30 days. Changed content replaces the previous copy only after verification.":
      "native.whileTheAppIsOpenSavedResourcesAreChecked",
  "Whole chapter": "native.wholeChapter",
  "Word mode": "native.wordMode",
  "Words, a phrase or a Scripture reference":
      "native.wordsAPhraseOrAScriptureReference",
  "Your saved data has not been reset.": "native.yourSavedDataHasNotBeenReset",
  "Your topics and public topics share this bookmark list. Downloading adds global memberships; your personal bookmarks remain independent.":
      "native.yourTopicsAndPublicTopicsShareThisBookmarkList",
};
