#!/usr/bin/env python3
"""Embed shared contract fixtures in test-only Dart for sandboxed native runners.

Android/iOS applications cannot open the checkout's test/fixtures directory.
The generated library is imported only by test/support helpers, never by lib/;
release packages therefore do not carry fixtures. --check detects stale copies.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / 'test/support/fixture_documents.dart'


def render():
    fixtures = ROOT / 'test/fixtures'
    paths = sorted({
        *fixtures.glob('dictionaries_v1/**/*.json'),
        *fixtures.glob('offline_study_v1/*.json'),
        *fixtures.glob('public_topic_*.json'),
        fixtures / 'bible_v3/rich_translation.json',
        fixtures / 'commentary_v1.json',
        fixtures / 'service_envelopes.json',
        fixtures / 'database_schema_v4.sql',
    })
    lines = [
        '// Generated by scripts/testing/embed_fixtures.py; do not edit.',
        '// Test-only fixture bytes, shared by host widgets and native sandboxes.',
        '// dart format off',
        "import 'dart:convert';",
        '',
        'bool fixtureExists(String path) => _documents.containsKey(path);',
        'String fixtureText(String path) =>',
        "    _documents[path] ?? (throw StateError('Unknown contract fixture: $path'));",
        'List<int> fixtureBytes(String path) => utf8.encode(fixtureText(path));',
        '',
        'const _documents = <String, String>{',
    ]
    for path in paths:
        body = path.read_text()
        if "'''" in body:
            raise ValueError(f'Unsupported raw delimiter in {path}')
        lines.append(f"  '{path.relative_to(fixtures).as_posix()}': r'''{body}''',")
    lines.extend(['};', ''])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text() != expected:
            parser.exit(1, 'Native fixtures are stale: run python3 scripts/testing/embed_fixtures.py\n')
    else:
        TARGET.write_text(expected)


if __name__ == '__main__':
    main()
